entity_webhook.webhook_field_mapping.*:
  type: config_entity
  label: 'Webhook Field Mapping'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Label'
    source_type:
      type: string
      label: 'Parent source type ID'
    entity_field:
      type: string
      label: 'Entity Field'
    is_identifier:
      type: boolean
      label: 'Is Identifier'
    resolver:
      type: string
      label: 'Value Resolver Plugin ID'
    resolver_config:
      type: sequence
      label: 'Resolver Configuration'
      sequence:
        type: ignore
        label: 'Configuration value'
    mutation_plugin:
      type: string
      label: 'Mutation Plugin ID'
    mutation_config:
      type: sequence
      label: 'Mutation Configuration'
      sequence:
        type: ignore
        label: 'Configuration value'

entity_webhook.webhook_source_type.*:
  type: config_entity
  label: 'Webhook Source Type'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Label'
    endpoint:
      type: string
      label: 'Parent endpoint ID'
    operation:
      type: string
      label: 'Entity operation (upsert or delete)'
    verification_plugin:
      type: string
      label: 'Verification Plugin ID'
    verification_config:
      type: sequence
      label: 'Verification Plugin Configuration'
      sequence:
        type: ignore
        label: 'Configuration value'

entity_webhook.webhook_endpoint.*:
  type: config_entity
  label: 'Webhook Endpoint'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Label'
    target_entity_type:
      type: string
      label: 'Target Entity Type'
    target_entity_bundle:
      type: string
      label: 'Target entity bundle'
    source_types:
      type: sequence
      label: 'Source Types'
      sequence:
        type: string
        label: 'Source Type ID'
