entity_webhook_polling.polling.*:
  type: config_entity
  label: 'Polling Configuration'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Label'
    status:
      type: boolean
      label: 'Status'
    cron_expression:
      type: string
      label: 'Cron Expression'
    polling_provider:
      type: string
      label: 'Polling Provider Plugin ID'
    polling_provider_config:
      type: sequence
      label: 'Polling Provider Configuration'
      sequence:
        type: ignore
        label: 'Configuration value'
    endpoint_id:
      type: string
      label: 'Webhook Endpoint ID'
    source_type_id:
      type: string
      label: 'Webhook Source Type ID'
